version: 3.1.55.{build}
skip_tags: true
image: Visual Studio 2017
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- ps: >-

    Push-Location "src/Noobot.Console/Configuration/"

    copy "config.default.json" "config.json"

    Pop-Location
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
- ps: >-
    dotnet build ".\Noobot.sln" -c "Release" -r "win-x64" -f "netcoreapp2.0"

before_package:
- cmd: dotnet publish ".\src\Noobot.Console\Noobot.Console.csproj" -c "Release" -r "win-x64" -f "netcoreapp2.0"
after_build:
- ps: >-
    $buildPath = Resolve-Path ".\src\Noobot.Console\bin\Release\*\*\publish"

    Write-Host "Zipping $buildPath"

    7z a noobot.zip "$buildPath\*"

test: off
artifacts:
- path: noobot.zip
deploy:
- provider: GitHub
  auth_token:
    secure: 8t4+xbVlkXA/FY3516ThrMibGxfCT7ZcSwyZw7KNwUlCH08KMPtznY2QphEn1n/z
  artifact: noobot.zip,/.*\.nupkg/
  draft: true
  on:
    branch: master