version: 3.1.55.{build}

skip_tags: true

image: Visual Studio 2017

configuration: Release

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'

before_build:
- ps: >-
    dotnet restore ".\Noobot.sln" -r "win-x64"

    Push-Location "src\Noobot.Console\Configuration\"

    copy "config.default.json" "config.json"
    Pop-Location
build: off

build_script: dotnet build -c "Release" -r "win-x64" -f "netcoreapp2.0"

after_build: dotnet pack  ".\src\Noobot.Core\Noobot.Core.csproj" --configuration Release --output ".\nupkgs" --no-build --no-restore --runtime "win-x64" 

test: off

nuget:
  project_feed: true
  disable_publish_on_pr: true

artifacts:
    -path: nupkgs\*.nupkg

deploy:
- provider: GitHub
  auth_token:
    secure: 8t4+xbVlkXA/FY3516ThrMibGxfCT7ZcSwyZw7KNwUlCH08KMPtznY2QphEn1n/z
  artifact: nupkgs\*.nupkg
  draft: true
  on:
    branch: master